#!/bin/bash
if [ "$EUID" -ne "0" ]; then
	echo "Must be run as superuser"
	exit 1
fi
echo "Searching for compiled binaries..."

bin_install() {
	ls | while read file
	do
		if echo "$(file "$file")" | grep -qi "executable" ; then
			echo "Installing $file..."
			cp -p "$file" /usr/bin
			echo "Done"
		fi
	done
}
bin_install
cp -p dsply/target/release/dsply /usr/bin

